[project]
name = "slide-tc"
version = "0.1.4"
description = "solve slide Tcaptcha"
authors = [{ name = "aioqzone" }]
maintainers = [
    { name = "aioqzone", email = "22952836+JamzumSum@users.noreply.github.com" },
]
license = "AGPL-3.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=12",
    "numpy==2.2.6; python_version == '3.10'",
    "numpy>=2.3.4; python_version >= '3.11'",
]

[dependency-groups]
dev = ["pre-commit", "ruff"]
test = [
    "pytest~=9.0",
    "pytest-asyncio~=1.3",
    "aioqzone>=1.9.6.dev1", "pychaosvm"
]

[tool.uv]
prerelease = "if-necessary-or-explicit"

[[tool.uv.index]]
name = "aioqzone-index"
url = "https://aioqzone.github.io/aioqzone-index/simple/"

[tool.uv.sources]
pychaosvm = { index = "aioqzone-index" }

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = "src"
log_cli = true
log_cli_level = "WARNING"
asyncio_default_fixture_loop_scope = "module"

[tool.ruff]
line-length = 99
