name: Test

on:
  pull_request:
    types:
      - review_requested
    branches:
      - beta
      - release

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.8"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install and Test
        env:
          TEST_UIN: ${{ secrets.TEST_UIN }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          echo "::group::Install Dependencies"
          poetry install --all-extras -n -vv
          echo "::endgroup::"

          echo "::group::pytest outputs"
          poetry run pytest test
          echo "::endgroup::"
